name: test-backend

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml

      - name: Analyze with SonarCloud
        working-directory: ./simple-api
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=hasnizmt13_tp-devops-correction-docker -Dsonar.organization=hasnizmt13 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
